m = 10000; %[kg] (requirement)
C_D = 1.2466; %[-] (guess) apollo 'Claus Weiland'
dCD_dM = 0; %[-] (guess)
C_L = 0.5; %[-] (guess)
LD = C_L/C_D; %[-] (calculation)
gamma = 0; %[rad] (guess)
phi =  0; %[rad] (guess)
chi = 0; %[rad] (guess)
R_m = 3390000;  %[m] 
h = 150000; %[m] (guess)
r = R_m + h; %[m] (calculation)
V0 = 7000; %[m/s] (requirement)
a = 301.5; %[m/s] (guess) wolfram alpha
M0 = V0/a; %[-] (calculation)
rho = 0.01328; %[kg/m^3] (guess) wolfram alpha
q0 = 0.5*rho*V0^2; %[N/m^2] (calculation)
d = 12; %[m] (requirement)
S = pi/4*d^2; %[m^2] (calculation)
D0 = C_D*q0*S; %[N] (calculation)
avv = -1/(m*V0)*(M0*dCD_dM*q0*S+2*D0);

A = [avv avg avR; agv agg agR; aRv aRg aRR]
