function dgamma_dt = diff_gamma(m,L,g,gamma,V,r,omega,phi,chi)


    dgamma_dt = 1/V * (...
                1/m * L - g * cos(gamma)            +...
                V^2 / r * cos(gamma)                +...
                2 * omega * V * cos(phi) * cos(chi) +...
                omega^2 * r * (cos(phi))^2 * (cos(gamma) + sin(gamma) * tan(phi) * sin(chi))...
                );
            
end