function dchi_dt = diff_chi(gamma,V,r,omega,phi,chi)


    dchi_dt =   1/V * (...
                -V^2/r * cos(gamma) * cos(chi) * tan(phi)                       +...
                2 * omega * V * (tan(gamma) * cos(phi) * sin(chi) - sin(phi))   +...
                - omega^2 * r / cos(gamma) * sin(phi) * cos(phi) * cos(chi)     ...
                );
            
end